export const TOKEN_TYPE = 'user'
export const NOTIF_SUCCESS_TYPE = 'success'
export const NOTIF_ERROR_TYPE = 'error'
export const NOTIF_WARNING_TYPE = 'warning'
export const SERVER_ERROR = 'Something went wrong with the server :('
export const WRONG_CREDENTIALS = 'Username/password is incorrect :('
export const LOGIN_SUCCESS_MSG = 'Successfully logged in :)'
export const LOGOUT_SUCCESS_MSG = 'Successfully logged out :)'
export const NOTIF_MID_RANGE_TIMEOUT = 3000
export const NOTIF_SHORT_RANGE_TIMEOUT = 1000
export const UNAUTHORIZED = 'User is not authorized :('
export const NOT_FOUND = 'Not found :('
export const FORBIDDEN = 'Forbidden :('
export const BAD_REQUEST = 'Bad request :('
