export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

// USER CONSTANTS
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const SET_USER_DATA_FAILURE = 'SET_USER_DATA_FAILURE'
export const SET_USER_DATA_REQUEST = 'SET_USER_DATA_REQUEST'
export const SET_USER_DATA_SUCCESS = 'SET_USER_DATA_SUCCESS'

// FILTERS_CONSTANTS
export const FETCH_LOCATIONS_REQUEST = 'FETCH_LOCATIONS_REQUEST'
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE'
export const SET_OPPORTUNITY_FILTER = 'SET_OPPORTUNITY_FILTER'

// PROFILE CONSTANTS
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST'
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE'
export const UPLOAD_USER_IMAGE_FAILURE = 'UPLOAD_USER_IMAGE_FAILURE'
export const UPLOAD_USER_IMAGE_REQUEST = 'UPLOAD_USER_IMAGE_REQUEST'
export const UPLOAD_USER_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS'
export const ADD_PROFILE_SOCIAL_LINKS = 'ADD_PROFILE_SOCIAL_LINKS'
export const CREATE_USER_PROFILE_REQUEST = 'CREATE_USER_PROFILE_REQUEST'
export const CREATE_USER_PROFILE_SUCCESS = 'CREATE_USER_PROFILE_SUCCESS'
export const CREATE_USER_PROFILE_FAILURE = 'CREATE_USER_PROFILE_FAILURE'
export const SELF_PROFILE = 'self'
export const PUBLIC_PROFILE = 'public'
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'
export const FETCH_PROFILE_POST_REQUEST = 'FETCH_PROFILE_POST_REQUEST'
export const FETCH_PROFILE_POST_SUCCESS = 'FETCH_PROFILE_POST_SUCCESS'
export const FETCH_PROFILE_POST_FAILURE = 'FETCH_PROFILE_POST_FAILURE'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

// OPPORTUNITIES_CONSTANTS
export const FETCH_USER_OPPORTUNITIES_REQUEST =
  'FETCH_USER_OPPORTUNITIES_REQUEST'
export const FETCH_USER_OPPORTUNITIES_SUCCESS =
  'FETCH_USER_OPPORTUNITIES_SUCCESS'
export const FETCH_USER_OPPORTUNITIES_FAILURE =
  'FETCH_USER_OPPORTUNITIES_FAILURE'
export const INTERNSHIP_POST_TYPE_KEY = 1
export const COMPETITION_POST_TYPE_KEY = 2
export const PROJECT_POST_TYPE_KEY = 3
export const SET_OPPORTUNITY_FILTER_TAB = 'SET_OPPORTUNITY_FILTER_TAB'
export const BOOKMARK_POST_REQUEST = 'BOOKMARK_POST_REQUEST'
export const BOOKMARK_POST_SUCCESS = 'BOOKMARK_POST_SUCCESS'
export const BOOKMARK_POST_FAILURE = 'BOOKMARK_POST_FAILURE'
export const APPLY_POST_REQUEST = 'APPLY_POST_REQUEST'
export const APPLY_POST_SUCCESS = 'APPLY_POST_SUCCESS'
export const APPLY_POST_FAILURE = 'APPLY_POST_FAILURE'
export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE'

// ORGANISATION CONSTANTS
export const FETCH_ORGANIZATIONS_LIST_REQUEST =
  'FETCH_ORGANIZATIONS_LIST_REQUEST'
export const FETCH_ORGANIZATIONS_LIST_SUCCESS =
  'FETCH_ORGANIZATIONS_LIST_SUCCESS'
export const FETCH_ORGANIZATIONS_LIST_FAILURE =
  'FETCH_ORGANIZATIONS_LIST_FAILURE'

// SKILLS CONSTANTS
export const FETCH_SKILLS_REQUEST = 'FETCH_SKILLS_REQUEST'
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS'
export const FETCH_SKILLS_FAILURE = 'FETCH_SKILLS_FAILURE'
export const ADD_SKILL_REQUEST = 'ADD_SKILL_REQUEST'
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS'
export const ADD_SKILL_FAILURE = 'ADD_SKILL_FAILURE'
export const REMOVE_SKILL_REQUEST = 'REMOVE_SKILL_REQUEST'
export const REMOVE_SKILL_SUCCESS = 'REMOVE_SKILL_SUCCESS'
export const REMOVE_SKILL_FAILURE = 'REMOVE_SKILL_FAILURE'
export const SEARCH_SKILLS = 'SEARCH_SKILLS'
export const REMOVE_ALL_SKILLS_REQUEST = 'REMOVE_ALL_SKILLS_REQUEST'
export const REMOVE_ALL_SKILLS_SUCCESS = 'REMOVE_ALL_SKILLS_SUCCESS'
export const REMOVE_ALL_SKILLS_FAILURE = 'REMOVE_ALL_SKILLS_FAILURE'
export const ADD_PROFILE_SKILLS = 'ADD_PROFILE_SKILLS'
export const SET_ADDED_SKILLS = 'SET_ADDED_SKILLS'

// POSTS CONSTANTS
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED'
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING'
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_LOADING = 'CREATE_POST_LOADING'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'
export const POST_FETCH_FAILURE = 'POST_FETCH_FAILURE'
export const POST_FETCH_LOADING = 'POST_FETCH_LOADING'
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS'
export const SET_CREATE_POST_TAB = 'SET_CREATE_POST_TAB'

// FOLLOW UNFOLLOW CONSTANTS
export const FOLLOW_UNFOLLOW_USER_REQUEST = 'FOLLOW_UNFOLLOW_USER_REQUEST'
export const FOLLOW_UNFOLLOW_USER_SUCCESS = 'FOLLOW_UNFOLLOW_USER_SUCCESS'
export const FOLLOW_UNFOLLOW_USER_FAILURE = 'FOLLOW_UNFOLLOW_USER_FAILURE'
